linters:
  enable:
    - gofmt
    - golint
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8