linters:
  presets:
    - bugs
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - unused
  disable:
    - gci
    - godox
    - wsl
    - exhaustruct
    - lll
    - varnamelen
    - nlreturn
    - gomnd
    - testpackage
    - depguard
    - musttag
    - tagalign
    - interfacebloat
    - inamedparam
    - godot
    - forbidigo
    - err113
    - ireturn
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100
  gosec:
    excludes:
      - G104  # Duplicate error checks
      - G114  # Use of net/http serve function that has no support for setting timeouts
      - G404  # Insecure random number source (math/rand)
  govet:
    check-shadowing: true

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - exp

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck